import { useEffect, useState } from 'react';
import {
  fetchTests,
  createTest as createTestApi,
  updateTest as updateTestApi,
  deleteTest as deleteTestApi,
} from './testApi';
import { toast } from 'react-toastify';

// Pulls the best error message
const getApiErrorMessage = (err) => {
  const data = err?.response?.data;

  const formatted = data?.errors?.formattedErrors;
  if (Array.isArray(formatted) && formatted.length > 0 && formatted[0]?.message) {
    return formatted[0].message;
  }

  if (typeof data?.message === 'string') return data.message;
  if (typeof data?.error?.message === 'string') return data.error.message;
  if (typeof err?.message === 'string') return err.message;

  return 'Request failed';
};

// Structure generated by AI. Modified to fit my models attributes.
export function useTests() {
  const [tests, setTests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [meta, setMeta] = useState({ total: 0, page: 1, limit: 10, numberOfPages: 1 });

  useEffect(() => {
    loadTests();
  }, []);

  async function loadTests(query = {}) {
    setLoading(true);
    try {
      const data = await fetchTests(query);
      setTests(data.tests);
      setMeta({
        total: data.total,
        page: data.page,
        limit: data.limit,
        numberOfPages: data.numberOfPages,
      });
    } catch (err) {
      toast.error(getApiErrorMessage(err));
      throw err;
    } finally {
      setLoading(false);
    }
  }

  async function createTest(payload) {
    try {
      const newTest = await createTestApi(payload); // already the test
      setTests((prev) => [newTest, ...prev]);
      toast.success('Test created');
      return newTest;
    } catch (err) {
      toast.error(getApiErrorMessage(err));
      throw err;
    }
  }

  async function updateTest(id, payload) {
    try {
      const updated = await updateTestApi(id, payload); // already the test
      setTests((prev) => prev.map((t) => (t._id === id ? updated : t)));
      toast.success('Test updated');
      return updated;
    } catch (err) {
      toast.error(getApiErrorMessage(err));
      throw err;
    }
  }

  async function deleteTest(id) {
    try {
      await deleteTestApi(id);
      setTests((prev) => prev.filter((t) => t._id !== id));
      toast.success('Test deleted');
      return true;
    } catch (err) {
      toast.error(getApiErrorMessage(err));
      throw err;
    }
  }

  return {
    tests,
    loading,
    meta,
    loadTests,
    createTest,
    updateTest,
    deleteTest,
  };
}
